name: Digit Admin Console Build workflow
on:
  push:
    branches: [ 'develop','console','master']
    paths:
      - 'health/micro-ui/web/micro-ui-internals/**'
  workflow_dispatch:
jobs:
  docker_image-build:
    outputs:
      run_job_digit_ui: ${{ steps.check_files.outputs.run_job_digit_ui }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io
      - name: Set Version from Tag or Branch
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}  # Use tag name for version
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Use branch name as version, replacing '/' with '-'
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
          else
            VERSION="latest"  # Default version if not a tag or branch
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Build and Push Docker image for workbench-ui
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/workbench-ui:${{ env.VERSION }}-${{ env.commit_hash }} -f  web/docker/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/workbench-ui:${{ env.VERSION }}-${{ env.commit_hash }}
        working-directory: health/micro-ui
